"""add_plan_id_to_publish_schedules

Revision ID: 62e35f418082
Revises: cb549e802a6e
Create Date: 2026-07-23 18:19:43.685578
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '62e35f418082'
down_revision: Union[str, None] = 'cb549e802a6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publish_schedules', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_publish_schedules_plan_id'), 'publish_schedules', ['plan_id'], unique=False)
    op.create_foreign_key(None, 'publish_schedules', 'content_plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publish_schedules', type_='foreignkey')
    op.drop_index(op.f('ix_publish_schedules_plan_id'), table_name='publish_schedules')
    op.drop_column('publish_schedules', 'plan_id')
    # ### end Alembic commands ###
