"""add_channel_link

Revision ID: 9d7cd982aa43
Revises: 62e35f418082
Create Date: 2026-07-23 20:33:19.692948
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9d7cd982aa43'
down_revision: Union[str, None] = '62e35f418082'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('channel_link', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'channel_link')
    # ### end Alembic commands ###
