"""add_topic_id_and_auto_publish_to_schedules

Revision ID: cb549e802a6e
Revises: d93fa4f12dea
Create Date: 2026-07-23 17:43:21.822826
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cb549e802a6e'
down_revision: Union[str, None] = 'd93fa4f12dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publish_schedules', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.add_column('publish_schedules', sa.Column('auto_publish', sa.Boolean(), nullable=False))
    op.alter_column('publish_schedules', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_publish_schedules_topic_id'), 'publish_schedules', ['topic_id'], unique=False)
    op.create_foreign_key(None, 'publish_schedules', 'content_topics', ['topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publish_schedules', type_='foreignkey')
    op.drop_index(op.f('ix_publish_schedules_topic_id'), table_name='publish_schedules')
    op.alter_column('publish_schedules', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('publish_schedules', 'auto_publish')
    op.drop_column('publish_schedules', 'topic_id')
    # ### end Alembic commands ###
