"""add_post_settings_to_content_plans

Revision ID: d93fa4f12dea
Revises: 3f9e866377cb
Create Date: 2026-07-23 17:16:28.248130
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd93fa4f12dea'
down_revision: Union[str, None] = '3f9e866377cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content_plans', sa.Column('post_settings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content_plans', 'post_settings')
    # ### end Alembic commands ###
